# Generated by Django 2.1 on 2018-12-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181216_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_article', to='webapp.Article', verbose_name='Статья'),
        ),
    ]
