# Generated by Django 2.1 on 2018-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181220_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
