# Generated by Django 2.1 on 2018-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181220_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
